services:
  - type: web
    name: atman-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: MONITOR_URL
        value: https://atman-monitor.onrender.com
      - key: STRIPE_PUB_KEY
        value: pk_live_XXXXXXXX
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
